# Generated by Django 4.2.21 on 2025-05-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("blocks", models.JSONField(default=list)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("content", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("drag_index", models.FloatField(blank=True, null=True)),
                (
                    "pageId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.page"
                    ),
                ),
            ],
            options={
                "ordering": ["drag_index"],
            },
        ),
    ]
