# Generated by Django 5.1.5 on 2025-02-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_page_slug_alter_page_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['drag_index']},
        ),
        migrations.AddField(
            model_name='block',
            name='drag_index',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
