# Generated by Django 5.1.5 on 2025-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_block_options_block_drag_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='drag_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
