# Generated by Django 4.2.20 on 2025-04-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_block_drag_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="settings",
            new_name="config",
        ),
    ]
